settings:
  advise_cla_signing: 
    - "true"
  mention_contributors_in_pull_requests:
    - "true"
  postprocess_jupyter_notebooks_with_nbfmt_py: true

synchronize:
  paths:
  - source: .
    exclude:
    - "**/_*"
    - "**/api_docs/*"
    - "**/FAILURES.md"
    - "**/index.*"
    - "**/README.*"
    - "**/sitemap.*"
    - "**/*.gitignore"
    - "**/*.yaml"
    - "**/*.yml"
